import { z } from "zod";

export const SessionEventSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("session.started"),
    sessionId: z.string(),
    workspacePath: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("session.completed"),
    sessionId: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("session.failed"),
    sessionId: z.string(),
    error: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("session.aborted"),
    sessionId: z.string(),
    reason: z.string().optional(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("session.meta"),
    sessionId: z.string(),
    title: z.string().optional(),
    model: z.string().optional(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("message.delta"),
    sessionId: z.string(),
    messageId: z.string(),
    role: z.enum(["assistant", "user", "system"]),
    text: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("message.completed"),
    sessionId: z.string(),
    messageId: z.string(),
    role: z.enum(["assistant", "user", "system"]),
    text: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("tool.started"),
    sessionId: z.string(),
    callId: z.string(),
    name: z.string(),
    input: z.unknown(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("tool.completed"),
    sessionId: z.string(),
    callId: z.string(),
    name: z.string(),
    ok: z.boolean(),
    output: z.unknown(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("permission.requested"),
    sessionId: z.string(),
    requestId: z.string(),
    toolName: z.string(),
    risk: z.enum(["low", "medium", "high"]),
    summary: z.string(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("permission.resolved"),
    sessionId: z.string(),
    requestId: z.string(),
    decision: z.enum(["allow", "deny", "allow_session"]),
    at: z.string(),
  }),
  z.object({
    type: z.literal("diff.updated"),
    sessionId: z.string(),
    path: z.string(),
    kind: z.enum(["create", "modify", "delete"]).optional(),
    before: z.string().optional(),
    after: z.string().optional(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("task.updated"),
    sessionId: z.string(),
    taskId: z.string(),
    title: z.string(),
    status: z.enum(["pending", "in_progress", "completed", "cancelled", "failed"]),
    detail: z.string().optional(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("terminal.output"),
    sessionId: z.string(),
    callId: z.string(),
    command: z.string(),
    stdout: z.string().optional(),
    stderr: z.string().optional(),
    code: z.number().nullable().optional(),
    ok: z.boolean(),
    at: z.string(),
  }),
  z.object({
    type: z.literal("usage.updated"),
    sessionId: z.string(),
    inputTokens: z.number(),
    outputTokens: z.number(),
    at: z.string(),
  }),
]);

export type SessionEvent = z.infer<typeof SessionEventSchema>;
